# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: The Workshop
    identifier: main
    weight: 10
  - name: About
    parent: main
    url: main/tour/
    weight: 10
  - name: News
    parent: main
    url: main/post/
    weight: 20
  - name: The 1st iLoc workshop
    parent: main
    url: https://sites.google.com/view/iloc-2022
    weight: 30
  - name: Participation
    identifier: participation
    weight: 30
  - name: Call for paper
    parent: participation
    url: participation/contribution/
    weight: 10
  - name: Call for poster
    parent: participation
    url: participation/poster/
    weight: 20
  - name: Registration guidelines
    parent: participation
    url: participation/registration/
    weight: 30
  - name: Schedule
    url: event
    weight: 40
  - name: Speakers
    url: people
    weight: 50
  - name: Organisation
    url: people
    weight: 60
