# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: The iLoc Workshop
    identifier: main
    weight: 10
  - name: About
    parent: main
    url: tour/
    weight: 10
  - name: News
    parent: main
    url: post/
    weight: 20
  - name: IEEE ITSC 2023
    parent: main
    url: https://2023.ieee-itsc.org
    weight: 30
  - name: The 1st iLoc workshop
    parent: main
    url: https://sites.google.com/view/iloc-2022
    weight: 40
  - name: Participation
    identifier: participation
    weight: 30
  - name: Call for paper
    parent: participation
    url: workshop2/cfp/
    weight: 10
  - name: Call for poster
    parent: participation
    url: workshop2/poster/
    weight: 20
  - name: Registration guidelines
    parent: participation
    url: workshop2/registration/
    weight: 30
  - name: Program
    url: workshop2/program
    weight: 40
  - name: Speakers
    url: speaker
    weight: 50
  - name: Organizers
    url: people
    weight: 60
